#!/usr/bin/env python3
"""Write the version resource embedded in the Windows executable.

Explorer's Details tab, the UAC prompt and most antivirus heuristics read this
block. An executable without one looks anonymous, which is exactly what an
unsigned download should avoid.

    python scripts/windows_version_info.py --output build/windows-version-info.txt

The company field carries the project name rather than an invented company:
this project has no legal entity behind it and claiming one would be false.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

TEMPLATE = """# Generated by scripts/windows_version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', {company!r}),
         StringStruct('FileDescription', {description!r}),
         StringStruct('FileVersion', {version!r}),
         StringStruct('InternalName', {internal!r}),
         StringStruct('LegalCopyright', {copyright!r}),
         StringStruct('OriginalFilename', {filename!r}),
         StringStruct('ProductName', {product!r}),
         StringStruct('ProductVersion', {version!r})])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def version_parts(version: str) -> tuple[int, int, int]:
    numbers = []
    for chunk in version.split('.')[:3]:
        digits = ''.join(character for character in chunk if character.isdigit())
        numbers.append(int(digits) if digits else 0)
    while len(numbers) < 3:
        numbers.append(0)
    return numbers[0], numbers[1], numbers[2]


def render() -> str:
    from app import APP_NAME, APP_TITLE, __version__

    major, minor, patch = version_parts(__version__)
    return TEMPLATE.format(
        major=major, minor=minor, patch=patch,
        version=__version__,
        company=APP_TITLE,
        description='Download video and audio with yt-dlp',
        internal=APP_NAME,
        # The project is released into the public domain; see LICENSE
        copyright='Released into the public domain (Unlicense)',
        filename=f'{APP_NAME}.exe',
        product=APP_TITLE,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--output', type=Path,
                        default=ROOT / 'build' / 'windows-version-info.txt')
    args = parser.parse_args(argv)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(), encoding='utf-8')
    print(f'wrote {args.output}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
